//
//  Test.swift
//  Psychotype
//
//  Created by mac on 12.01.2021.
//

import Foundation

struct Test {
    let nameOfTest : String
    let questions : [Question]
    let descriptionOfTest : String
    
    static func getTests() -> [Test]{
        return [
            Test(nameOfTest: "Уверены ли вы в себе",
                 questions: [Question(text: "Я боюсь делать возврат бракованного товара в магазин", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident), Answer(text: "Не всегда", type: .almostConfident), Answer(text: "Не боюсь", type: .confident)]),
                             Question(text: "Если я сделал(-а) действительно что-то стоящее, то не стесняюсь говорить об этом", type: .single,
                                      answers: [Answer(text: "Да", type: .confident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Боюсь", type: .notConfident)]),
                             Question(text: "Если кто-то пытается пролезть вне очереди, то получит от меня замечание", type: .single,
                                      answers: [Answer(text: "Да", type: .confident),
                                                Answer(text: "Мне будет не удобно, но я  сделаю", type: .almostConfident),
                                                Answer(text: "Нет", type: .notConfident)]),
                             Question(text: "Если я не согласен (-на) с чьей-то точкой зрения, то не стесняюсь выразить свою", type: .single, answers: [Answer(text: "Да", type: .confident),                                                                      Answer(text: "Не всегда", type: .almostConfident),
                                                                                                                                                                                                                      Answer(text: "Стесняюсь", type: .notConfident)]),
                             Question(text: "Я боюсь звонить незнакомому человеку", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Нет", type: .confident)]),
                             Question(text: "Мне очень сложно даются собеседования при устройстве на работу.", type: .ranged,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Нет", type: .confident)]),
                             Question(text: "Часто, многие люди используют меня в своих интересах.", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Иногда", type: .almostConfident),
                                                Answer(text: "Нет", type: .confident)]),
                             Question(text: "Мне нравится заводить знакомства с новыми людьми.",  type: .ranged,
                                      answers: [Answer(text: "Да", type:.confident),
                                                Answer(text: "Скорее да", type: .almostConfident),
                                                Answer(text: "Нет", type: .notConfident)]),
                             Question(text: "Делая покупку на рынке(авито), я не торгуюсь с продавцом.", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Иногда", type: .almostConfident),
                                                Answer(text: "Почти всегда торгуюсь", type: .confident)]),
                             Question(text: "В ссоре я иногда переживаю, за то что могу покраснеть или начать запинаться", type: .single, answers: [Answer(text: "Да", type: .notConfident),
                                                                                                                                                                                                                  Answer(text: "Не всегда", type: .almostConfident),
                                                                                                                                                                                                                  Answer(text: "Нет", type: .confident)]),
                             Question(text: "Если в общественном месте, рядом сидящие люди, мешают мне своими разговорами, то я прошу их разговаривать потише", type: .single,
                                      answers: [Answer(text: "Да", type: .confident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Нет", type: .notConfident)]),
                             Question(text: "Если кто-то меня раздражает, то я изо всех сил стараюсь не подавать виду", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Нет", type: .confident)]),
                             Question(text: "Если меня не устраивает обслуживание, то я без стеснений могу оставить жалобу", type: .single, answers: [Answer(text: "Да", type: .confident),
                                                                                                                                                                                                                       Answer(text: "Не всегда", type: .almostConfident),
                                                                                                                                                                                                                       Answer(text: "Нет", type: .notConfident)]),
                             Question(text: "Настойчивость - это не про меня", type: .single, answers: [Answer(text: "Да", type: .notConfident),                                                            Answer(text: "Не всегда", type: .almostConfident),
                                                                                                                                 Answer(text: "Нет", type: .confident)]),
                             Question(text: "Иногда я стесняюсь задать вопрос, чтобы не показаться глупым", type: .single,
                                      answers: [Answer(text: "Да", type: .notConfident),
                                                Answer(text: "Не всегда", type: .almostConfident),
                                                Answer(text: "Нет", type: .confident)])],
                 descriptionOfTest: "Этот тест поможет вам узнать на сколько вы уверены в себе.\nУверенность в себе — это залог успеха в большинстве случаев. Порой реальные навыки оказываются не настолько решающими, как адекватная самооценка и умение себя правильно преподнести. Определить уровень веры в себя поможет этот тест."),
            Test(nameOfTest: "Определение направленности личности",
                 questions: [Question(text: "Наибольшее удовлетворение я получаю от:", type: .single,
                                      answers: [Answer(text: "Одобрения моей работы", type: .I), Answer(text: "Сознания того, что работа сделана хорошо", type: .D), Answer(text: "Сознания того, что меня окружают друзья.", type: .O)]),
                             Question(text: "Если бы я играл в футбол (волейбол, баскетбол), то я хотел бы быть:", type: .single,
                                      answers: [Answer(text: "Тренером, который разрабатывает тактику игры", type: .D),
                                                Answer(text: "Известным игроком", type: .I),
                                                Answer(text: "Выбранным капитаном команды", type: .O)]),
                             Question(text: "По-моему, лучшим педагогом является тот, кто:", type: .single,
                                      answers: [Answer(text: "Проявляет интерес к учащимся и к каждому имеет индивидуальный подход", type: .I),
                                                Answer(text: "Вызывает интерес к предмету так, что учащиеся с удовольствием углубляют свои знания в этом предмете", type: .D), Answer(text: "Создает в коллективе такую атмосферу, при которой никто не боится высказать свое мнение", type: .O)]),
                             Question(text: "Мне нравится, когда люди:", type: .single, answers: [Answer(text: "Радуются выполненной работе", type: .D), Answer(text: "С удовольствием работают в коллективе", type: .O), Answer(text: "Стремятся выполнить свою работу лучше других", type: .I)]),
                             Question(text: "Лучшими друзьями я считаю тех:", type: .single,
                                      answers: [Answer(text: "С кем складываются хорошие взаимоотношения", type: .O), Answer(text: "На кого всегда можно положиться", type: .D),
                                                Answer(text: "Кто может многого достичь в жизни", type: .I)]),
                             Question(text: "Больше всего я не люблю:", type: .single, answers: [Answer(text: "Когда у меня что-то не получается", type: .D), Answer(text: "Когда портятся отношения с товарищами", type: .O), Answer(text: "Когда меня критикуют", type: .I)]),
                             Question(text: "Наибольших успехов я добиваюсь, когда:", type: .single, answers: [Answer(text: "Работаю с людьми, которые мне симпатичны", type: .O), Answer(text: "У меня интересная работа", type: .D), Answer(text: "Мои усилия хорошо вознаграждаются", type: .I)]),
                             Question(text: "Для меня важнее всего знать:", type: .single,
                                      answers: [Answer(text: "Что я хочу сделать", type: .I), Answer(text: "Как достичь цели", type: .D), Answer(text: "Как организовать людей для достижения цели", type: .O)]),
                             Question(text: "Человек должен стремиться к тому, чтобы:", type: .single,
                                      answers: [Answer(text: "Другие были им довольны", type: .O), Answer(text: "Прежде всего выполнить свою задачу", type: .D), Answer(text: "Его не нужно было упрекать за выполненную работу", type: .I)]),
                             Question(text: "Лучше всего я отдыхаю в свободное время:", type: .single,
                                      answers: [Answer(text: "В общении с друзьями", type: .O), Answer(text: "Просматривая развлекательные фильмы", type: .I), Answer(text: "Занимаясь своим любимым делом", type: .D)])],
                 descriptionOfTest: "С помощью методики выявляются следующие направленности: направленность на себя, направленность на общение или направленность на дело.\n\nСтарайтесь не задумываться долго над ответами, выбирайте варианты интуитивно, тогда результаты будут более достоверными."),
            Test(nameOfTest: "Тип темперамента",
                 questions: [Question(text: "Я несдержан(а) и вспыльчив(а)", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я суетлив(а) и неусидчив(а)", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я люблю отстаивать свою точку зрения", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я часто являюсь инициатором всевозможных мероприятий", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Мне трудно соблюдать определенный ритм в работе", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я быстро принимаю решения", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я всегда настойчиво иду к поставленной цели", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "У меня часто без особых причин меняется настроение", type: .yesNo, answers: [Answer(text: "Да", type: .choleric), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я энергичен и всегда знаю, куда направить свою энергию", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Неудачи я переживаю довольно легко", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Мне легко приспособиться к практически любым обстоятельствам", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я легко включаюсь в новую работу, а также переключаюсь с одного вида деятельности на другой", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я общителен и отзывчив, у меня много друзей", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я часто принимаю поспешные, необдуманные решения", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "У меня высокая работоспособность, я очень вынослив", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я легко включаюсь в новую работу, а также переключаюсь с одного вида деятельности на другой", type: .yesNo, answers: [Answer(text: "Да", type: .sanguine), Answer(text: "Нет", type: .none)]),
                             Question(text: "Во всех своих делах я придерживаюсь определенной последовательности", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я спокойно переношу ожидание", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Если мне нечего сказать, я предпочитаю молчать", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "В работе и в жизни я придерживаюсь привычной схемы", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Моя речь размеренна и спокойна, без яркой эмоциональной окраски", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я медленно втягиваюсь в работу или переключаюсь с одного вида деятельности на другой", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Мне трудно адаптироваться к новой обстановке", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Контакт с новыми людьми я налаживаю постепенно", type: .yesNo, answers: [Answer(text: "Да", type: .phlegmatic), Answer(text: "Нет", type: .none)]),
                             Question(text: "В незнакомой обстановке я чувствую себя растерянным", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я спокойно переношу одиночество", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Иногда я надолго ухожу в себя", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я бываю мнительным и подозрительным", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Меня легко обидеть", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Я предпочитаю скрывать свои мысли от окружающих", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Порой я не верю в свои силы", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)]),
                             Question(text: "Мне трудно заговорить с незнакомым человеком", type: .yesNo , answers: [Answer(text: "Да", type: .melancholic), Answer(text: "Нет", type: .none)])
                 ],
                 descriptionOfTest: "Когда-то давно древнегреческий врач Гиппократ выделил четыре типа темперамента. Эта классификация актуальна и по сей день. Однако «чистые» холерики, сангвиники, флегматики и меланхолики встречаются очень редко.\n\nБольшинство людей относится к так называемым смешанным типам темперамента. Им присущи черты разных типов темперамента, один из которых, как правило, преобладает"),
            
            Test(nameOfTest: "Кто вы - Интроверт или Экстраверт",
                 questions: [Question(text: "В один и тот же день запросто можете посмотреть два кинофильма, концерта, пьесы и др., назначить несколько встреч и успеть только на одну-две", type: .yesNo,
                                      answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы легко запоминаете лица, случаи, биографии, но труднее формулы и чужие высказывания", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Даже незначительного события достаточно, чтобы вы приостановили принятие важного решения", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Иногда одного большого мероприятия для вас достаточно на целый месяц", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы любите поесть, повеселиться в компании. Избегаете одиночества. Вы относитесь к категории жизнерадостных людей и ищете контакта с себе подобными, избегаете замкнутых людей", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Любите говорить речи, тосты. В компании любите быть на виду", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "У вас друзей немного. Вы трудно сближаетесь с людьми", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             
                             Question(text: "Вы лучше запоминаете основную идею, чем подробности", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "У вас неважное настроение, когда телевизор и радиоприемник неисправны. Вы чувствуете себя одиноким и оторванным от мира, если телефон отключен", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Быстро входите в контакт с незнакомыми людьми и легко ориентируетесь в новой обстановке, без особых затруднений выходите из сложных ситуаций", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы предпочитаете иметь дело с меньшим, но отреферированным объемом информации, чем со всем потоком сообщений", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы не любите суеты, громкой музыки, шумных компаний", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Быстро принимаете решения, способны на риск, хотя он не всегда оправдан", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Командировки для вас - развлечение, и вы их принимаете с радостью", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы чувствуете себя более свободно и непринужденно в домашней обстановке", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы принципиальный человек и стараетесь строго следовать своим принципам", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вас очень интересует, какое впечатление вы производите на окружающих", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы чувствуете себя комфортнее в коллективе, чем на едене", type: .yesNo, answers: [Answer(text: "Да", type: .extrover), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вы внимательно следите за своим здоровьем, считаете, что лучше лишний раз принять профилактическое лекарство, чем потом лечить болезнь", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)]),
                             Question(text: "Вам частенько говорят, что нужно проще смотреть на некоторые вещи", type: .yesNo, answers: [Answer(text: "Да", type: .introvert), Answer(text: "Нет", type: .none)])],
                 descriptionOfTest: "В книге швейцарского ученого Карла Г. Юнга «Психологические типы» впервые для психологической характеристики были использованы понятия «экстраверт» и «интраверт».\nЭкстраверты стремятся к расширению деловых контактов, использованию всех возможностей. Интраверты, напротив, контакты ограничивают, замкнуты в себе, отгораживаются от окружающих, делают впрок необходимые запасы, не допускают лишних расходов, берегут силы. Попробуйте определить, к какому психологическому типу вы принадлежите"),
            Test(nameOfTest: "Оценка способностей к саморазвитию",
                 questions: [Question(text: "Выберите, какая характеристика Вам более всего подходит?"
                                      , type: .single,
                                      answers: [Answer(text: "Целеустремленный", type: .highAbility), Answer(text: "Трудолюбивый", type: .averageAbility), Answer(text: "Отзывчивый", type: .lowAbility)]),
                             Question(text: "Как Вы относитесь к планированию своей работы на год, месяц, ближайшую неделю, день?", type: .single, answers: [Answer(text: "Я пытаюсь это делать, но не регулярно", type: .averageAbility), Answer(text: "Думаю, что чаще всего это пустая трата времени", type: .lowAbility), Answer(text: "Положительно, так как я давно это делаю", type: .highAbility)]),
                             Question(text: "Что Вам больше всего мешает профессионально самосовершенствоваться, лучше учиться?", type: .single, answers: [Answer(text: "Нет достаточно времени", type: .highAbility), Answer(text: "Нет подходящей литературы и условий", type: .averageAbility), Answer(text: "Не всегда хватает силы воли и настойчивости", type: .lowAbility)]),
                             Question(text: "Каковы типичные причины Ваших ошибок и промахов?", type: .single,
                                      answers: [Answer(text: "Переоцениваю свои способности", type: .averageAbility), Answer(text: "Невнимательность", type: .lowAbility), Answer(text: "Не до конца все продумываю", type: .highAbility)]),
                             Question(text: "Выберите, какая характеристика Вам более всего подходит?", type: .single,
                                      answers: [Answer(text: "Настойчивый", type: .averageAbility), Answer(text: "Усидчивый", type: .highAbility), Answer(text: "Доброжелательный", type: .lowAbility)]),
                             Question(text: "Выберите, какая характеристика Вам более всего подходит?", type: .single,
                                      answers: [Answer(text: "Решительный", type: .averageAbility), Answer(text: "Любознательный", type: .highAbility), Answer(text: "Справедливый", type: .lowAbility)]),
                             Question(text: "Что из это представляет для вас наибольший познавательный интерес?", type: .single, answers: [Answer(text: "Истории из жизни людей", type: .lowAbility), Answer(text: "Научная фантастика", type: .averageAbility), Answer(text: "Психология", type: .highAbility)]),
                 Question(text: "Что чаще всего Вы делаете, когда у Вас появляется свободное время?"
                          , type: .single, answers: [Answer(text: "Занимаюсь любимым делом, у меня есть хобби", type: .averageAbility),
                                                     Answer(text: "Читаю литературу на интересующую тему", type: .highAbility),
                                                     Answer(text: "Провожу время с друзьями, либо в кругу семьи", type: .lowAbility)]),
                 Question(text: "Выберите, какая характеристика Вам более всего подходит?"
                          , type: .single, answers: [Answer(text: "Генератор идей", type: .highAbility), Answer(text: "Критик", type: .averageAbility), Answer(text: "Организатор", type: .lowAbility)]),
                 Question(text: "Кем бы Вы могли себя максимально реализовать?", type: .single, answers: [Answer(text: "Спортсменом", type: .lowAbility),
                                                                                                                                                Answer(text: "Ученым", type: .highAbility),
                                                                                                                                                Answer(text: "Художником", type: .averageAbility)]),
                 Question(text: "Какой из трех принципов Вам ближе всего и которого Вы придерживаетесь чаще всего?", type: .single, answers: [Answer(text: "Живи и наслаждайся жизнью", type: .lowAbility), Answer(text: "Жить, чтобы больше знать и уметь", type: .highAbility), Answer(text: "Жизнь прожить - не поле перейти", type: .averageAbility)]),
                 Question(text: "Кто ближе всего к Вашему идеалу?", type: .single, answers: [Answer(text: "Человек здоровый, сильный духом", type: .lowAbility), Answer(text: "Человек, много знающий и умеющий", type: .highAbility), Answer(text: "Человек независимый и уверенный в себе", type: .averageAbility)]),
                 Question(text: "Удастся ли Вам в жизни добиться того, о чем Вы мечтаете?", type: .single, answers: [Answer(text: "Думаю, что да", type: .highAbility), Answer(text: "Скорее всего да", type: .averageAbility), Answer(text: "Как повезет", type: .lowAbility)]),
                 Question(text: "Какие фильмы Вам больше всего нравятся?", type: .single, answers: [Answer(text: "Приключенческие и романтические", type: .averageAbility), Answer(text: "Комедийно-развлекательные", type: .lowAbility), Answer(text: "Философские", type: .highAbility)]),
                 Question(text: "Представьте себе, что Вы заработали миллион. Куда бы Вы предпочли его истратить?", type: .single, answers: [Answer(text: "Путешествовал бы и посмотрел мир", type: .averageAbility), Answer(text: "Поехал бы учиться за границу или вложил бы деньги в любимое дело", type: .highAbility), Answer(text: "Купил бы коттедж с бассейном, мебель, шикарную машину и жил бы в свое удовольствие", type: .lowAbility)])] ,
                 descriptionOfTest: "Самообразование, как и иные формы образования, помогает человеку лучше понимать происходящие в его жизни процессы, их причинно-следственные связи и, что главное – позволяет человеку обрести необходимый теоретический и практический опыт с минимальной сторонней помощью, что гораздо более эффективно приучает и помогает ему анализировать и принимать самостоятельные жизненные решения.\nДанный тест позволит определить уровень способностей к саморазвитию и самообразованию"),
            Test(nameOfTest: "Тест на нервозность",
                 questions: [Question(text: "Раздражает ли вас, когда какой-то человек кашляет в вашу сторону?", type: .single,
                                      answers: [Answer(text: "Очень", type: .nervous),
                                                Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас, когда кто-то грызет ногти?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас, когда кто-то пытается учить вас, что и как нужно делать?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас, когда вам пытаются пересказать сюжет фильма(сериала), который вы только собираетесь посмотреть?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас, когда вам дарят ненужные предметы?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас громкий разговор в общественном транспорте?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас слишком сильный запах духов?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас человек, который жестикулирует во время разговора?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                             Question(text: "Раздражает ли вас чрезмерная близость собеседника (допустим, в трамвае в час пик)?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Вас раздражают странно одетые люди?"
                          , type: .single,
                          answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Вас раздражает непунктуальность?", type: .single, answers: [Answer(text: "Очень", type: .nervous), Answer(text: "Не особо", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Пустяк может привести вас в ярость?", type: .single, answers: [Answer(text: "Да", type: .nervous), Answer(text: "Не всегда", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Если вас в чем-то обвиняют, то вы чувствуете сильное волнение?", type: .ranged, answers: [Answer(text: "Да", type: .nervous), Answer(text: "Не всегда", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Визит к врачу приводит вас в ужас?", type: .single, answers: [Answer(text: "Да", type: .nervous), Answer(text: "Не всегда", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)]),
                 Question(text: "Вам необходимо учится или работать в полной тишине?", type: .single, answers: [Answer(text: "Да", type: .nervous), Answer(text: "Не всегда", type: .notVeryNervous), Answer(text: "Нет", type: .notNervous)])],
                 descriptionOfTest: "Нагрузка на нашу нервную систему увеличивается с ростом ритма современной жизни. Эта нагрузка все чаще начинает проявлять себя в излишней раздражительности, вспыльчивости и нервозности. Насколько хорошо у нас получается совладать собой в ответственный и критический момент? Как же мы справляемся с раздражителями, которые присутствуют в нашей жизни каждый день? Хотя бы приблизительный ответ на эти вопросы, возможно, даст этот тест."),
            Test(nameOfTest: "Тест на уровень стресса",
                 questions: [Question(text: "Как часто вы чувствуете напряжение?", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Как часто я замечаю за собой суетливость?", type: .ranged, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Испытываю проблемы при засыпании, долго не удается заснуть", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Бываете ли вы забывчивым даже в ситуациях, когда это недопустимо?", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Чувствуете ли вы себя одиноким и никому не нужным?", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "У вас часто меняется настроение?", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text:"Часто ли вы испытываете постоянное ощущение усталости?", type: .ranged, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Как часто вы испытываете необъяснимое беспокойство?", type: .ranged, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Испытываете ли вы проблемы пищеварительной системы?", type: .single, answers: [Answer(text: "Почти всегда", type:.stressful ), Answer(text: "Иногда", type: .notVeryStressfull), Answer(text: "Почти никогда", type: .notStressfull)]),
                             Question(text: "Какое у вас обычно настроение?", type: .single, answers: [Answer(text: "Каждый день беспричинное раздражение", type: .stressful),                                          Answer(text: "Бывают неприятные моменты, но в целом всё хорошо", type: .notVeryStressfull), Answer(text: "Замечательное, наслаждаюсь каждым днём", type: .notStressfull)]),
                             Question(text: "Как вы чувствуете себя в компании на большой вечеринке?", type: .single, answers: [Answer(text: "Хорошо, мне нравится общаться с людьми", type: .notStressfull), Answer(text: "В целом ничего особенного. С трудом завожу новые знакомства", type: .notVeryStressfull), Answer(text: "Не очень. Часто я чувствую себя одиноко даже среди людей", type: .stressful)]),
                             Question(text: "Как у вас с аппетитом?", type: .single,
                                      answers: [Answer(text: "Я постоянно забываю поесть, просто не голоден(a)", type: .stressful), Answer(text: "Стараюсь не пропускать завтрак, обед и ужин", type: .notVeryStressfull), Answer(text: "Хороший аппетит, я регулярно ем полезные продукты", type: .notStressfull)]),
                             Question(text: "Вы делитесь своими переживаниями с другими людьми?", type: .single,
                                      answers: [Answer(text: "Нет, я полностью оборвал связи с другими людьми", type: .stressful), Answer(text: "Иногда могу разоткровенничаться, но некоторые вещи всё же держу в себе", type: .notVeryStressfull), Answer(text: "Да, семья и друзья всегда поддерживают меня", type: .notStressfull)]),
                             Question(text: "Как вы можете описать своё самочувствие в целом?", type: .single, answers: [Answer(text: "Бывает и лучше", type: .stressful), Answer(text: "Хорошее. Временами наваливается усталость, но это нормально", type: .notVeryStressfull), Answer(text: "Отличное самочувствие! Всегда готов горы свернуть!", type: .notStressfull)])
                                                            ],
                 descriptionOfTest: "Стресс в нашей жизни стал нормой. Даже если происходят радостные события, наша психика и наш организм испытывает стресс. А, как известно, стрессы могут приводить к депрессиям и психозам.\nТест на стресс предназначен для диагностики нервной и эмоциональной напряженности и выявления вашего уровня стресса.\nСтарайтесь не задумываться долго над ответами, выбирайте варианты интуитивно, тогда результаты будут более достоверными.")
        ]
    }
}

